# -*- coding: utf-8 -*-
"""eda project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHm2JDoy9_wxtjOnih3WKZuEl5hQ_hBz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/employee_salary_dataset.csv")

df

df.head()

df.tail()

sns.barplot(x="Department", y="Monthly_Salary", data=df)
plt.xlabel("Department")
plt.ylabel("Salary")
plt.title("Department vs Salary")
plt.show()

sns.histplot(df["Monthly_Salary"], bins=5, kde=True)
plt.xlabel("Salary")
plt.ylabel("Frequency")
plt.title("Distribution of Monthly Salary")
plt.show()

plt.boxplot(df["Monthly_Salary"])
plt.ylabel("Salary")
plt.title("Box Plot of Salary")
plt.show()

corr = df[["Experience_Years","Age","Monthly_Salary"]].corr()

sns.heatmap(corr, annot=True)
plt.title("Correlation Matrix of Employee Data")
plt.show()

plt.scatter(df["Experience_Years"], df["Monthly_Salary"])
plt.xlabel("Experience_Years")
plt.ylabel("Salary")
plt.title("Experience vs Salary")
plt.show()

plt.pie(dept_count, labels=dept_count.index, autopct='%1.1f%%')
plt.title("Department Distribution")
plt.show()

